# Generated by Django 4.0.6 on 2022-07-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
        ('order_item_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction_app.transaction'),
        ),
    ]
