# Generated by Django 4.0.6 on 2022-08-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_item_app', '0002_alter_orderitem_options_alter_orderitem_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
